spring:
  jackson:
    default-property-inclusion: non_null
  cloud:
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: twitch
      client:
        config:
          twitch-api:
            url: https://api.twitch.tv/helix
            loggerLevel: basic
            default-request-headers:
              Client-Id: 9suzsrza7jrmho88chvbsupmvvyu6o
  security:
    oauth2:
      client:
        registration:
          twitch:
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            client-id: 9suzsrza7jrmho88chvbsupmvvyu6o
            client-secret: cugi6ixthv3lm2b0watndd7ov40m7s
        provider:
          twitch:
            token-uri: https://id.twitch.tv/oauth2/token

  datasource:
    url: jdbc:mysql://${DATABASE_URL:localhost}:3306/twitch?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: "classpath:database-init.sql"

  cache:
    caffeine:
      spec: expireAfterWrite=1m

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG #Incoming HTTP request
    com.laioffer.twitch.external.TwitchApiClient: DEBUG
    org.springframework.jdbc.core: DEBUG # SQL